# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hi < Formula
  desc "Hi"
  homepage "https://example.com"
  version "24.2.54"
  depends_on :macos

  on_arm do
    url "https://github.com/5g6g/test/releases/download/v24.2.54/hi-darwin-arm64.zip"
    sha256 "3524175ac2f7bbf6a24a87af0872a9a23c5edc8425b191b330f06323249cbf4a"

    def install
      bin.install "hi"
      generate_completions_from_executable(bin/"hi", "generate", "shell-completion", base_name: "hi")
    end
  end

  def caveats
    <<~EOS
      Nothing.
    EOS
  end
end
